repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        files: ^extensions/
        exclude: ^extensions/tests/|^extensions/docs/
      - id: end-of-file-fixer
        files: ^extensions/
        exclude: ^extensions/tests/|^extensions/docs/
      - id: trailing-whitespace
        files: ^extensions/
        exclude: ^extensions/tests/|^extensions/docs/

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length=125"]
        types: [file, python]
        files: ^extensions/
        exclude: ^extensions/tests/|^extensions/docs/

  # - repo: https://github.com/PyCQA/isort
  #   rev: 6.0.1
  #   hooks:
  #     - id: isort
  #       args: ["--line-length=125", "--profile=black"]
  #       types: [file, python]
  #       files: ^extensions/
  #       exclude: ^extensions/tests/|^extensions/docs/
  #       skip_glob: ["**/__init__.py"] 

  - repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: ["--ignore=E203,W503,W605", "--max-line-length=125"]
        types: [file, python]
        files: ^extensions/
        exclude: ^extensions/tests/|^extensions/docs/

  - repo: https://github.com/hhatto/autopep8
    rev: v2.3.2
    hooks:
      - id: autopep8
        types: [file, python]
        files: ^extensions/
        exclude: ^extensions/tests/|^extensions/docs/

  - repo: https://github.com/aws-samples/automated-security-helper
    rev: 'v3.0.0'
    hooks:
        - id: ash
          stages: [ manual ]
          # uncomment the line below if using "finch" on MacOS
          # args: [ "-f" ]
          files: ^extensions/
          exclude: ^extensions/tests/|^extensions/docs/

  - repo: https://github.com/sbrunner/pre-commit-copyright
    rev: 1.6.1
    hooks:
      - id: copyright
        name: update copyright
        exclude: |
          (?x)^(
            doc/.*|
            ^\..+|
            .+\.md|
            test/data/.*|
            LICENSE|
            tox.ini|
            pyproject.toml|
            setup.cfg|
            setup.py|
            py.typed|
            docs/|
            tests/
          )$
      - id: copyright-required
        name: require copyright
        exclude: |
          (?x)^(
            doc/.*|
            ^\..+|
            .+\.md|
            test/data/.*|
            LICENSE|
            tox.ini|
            pyproject.toml|
            setup.cfg|
            setup.py|
            py.typed|
            docs/|
            tests/
          )$
