repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: '\.proto$'
    -   id: end-of-file-fixer
-   repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
    -   id: black
        args: [--line-length=79]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        # We ignore the following because we use black to handle code-formatting
        # E203: Whitespace before ':'
        # E501: Line too long
        # E701: multiple statements on one line (colon)
        # E704: multiple statements on one line (def)
        # W503: Line break occurred before a binary operator
        args:
            [
            --extend-ignore, "E203,E501,E701,E704,W503"
            ]
-  repo: https://github.com/pycqa/isort
   rev: 5.12.0
   hooks:
   -   id: isort
       args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.358
    hooks:
    - id: pyright
      exclude: '\.proto$'
