# Copyright 2023-2025 Amazon.com, Inc. or its affiliates.

name: osml_model_runner
channels:
  - conda-forge
dependencies:
  - conda-forge::python=3.13.1
  - conda-forge::gdal=3.12.0
  - conda-forge::proj=9.7.0
  - conda-forge::openjpeg=2.5.4
