---
# Build jobs for Model Runner Service - Green Environment
#

build:
  extends: .docker_build_template
  variables:
    # Green environment uses GDAL base image
    BASE_IMG: ${GDAL_BASE_IMG}
    TARGET: "runner"
    PYTHON_BINARY: "python3.13"
    PIP_BINARY: "pip3.13"