---
# Build
#
# Jobs that will build the Model Runner and push it to the container registry.
#

build:
  stage: build
  tags: [dind]
  before_script:
    # Login to iron bank per instructions here: https://discourse.gs.mil/t/how-do-i-use-platform-one-iron-bank-hosted-images-at-nga/5187/2
    - docker login -u ${REGISTRY1_USERNAME} -p ${REGISTRY1_PASSWORD} registry1.dso.mil
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - |
      docker build --target runner \
                    -f docker/Dockerfile \
                    --build-arg PIP_INDEX_URL=$PIP_INDEX_URL \
                    --build-arg BASE_IMG=${GDAL_BASE_IMG} \
                    --build-arg CI=${CI} \
                    --build-arg NEXUS_AUTH=${NEXUS3_USER}:${NEXUS3_PASSWORD} \
                    --tag $MODEL_RUNNER_IMAGE .
    - docker push $MODEL_RUNNER_IMAGE
