---
# Orange Wormhole Trigger
#
# Jobs that will trigger the container wormhole process
#

trigger-semver:
  extends: .wormhole_template
  variables:
    # Override variables as needed
    IMAGE_PATH: $CI_REGISTRY_IMAGE/$MICROSERVICE
    TAG: $CURRENT_TAG
    DOMAIN: BOTH
