---
# Orange Wormhole Trigger
#
# Jobs that will trigger the container wormhole process
#

trigger-semver:
  stage: trigger
  variables:
    IMAGE_PATH: $CI_REGISTRY_IMAGE/$MICROSERVICE
    # Image Tag
    TAG: $CURRENT_TAG
    # Domain to send image to: SC/TC/BOTH
    DOMAIN: BOTH
  trigger:
    project: wormhole/container-movement-pipelines/container-up

trigger-stable:
  stage: trigger
  variables:
    IMAGE_PATH: $CI_REGISTRY_IMAGE/$MICROSERVICE
    # Image Tag
    TAG: stable
    # Domain to send image to: SC/TC/BOTH
    DOMAIN: BOTH
  trigger:
    project: wormhole/container-movement-pipelines/container-up