### GitLab Tag Version Stable Job
#

tag_stable:
  stage: build
  extends: .skopeo
  script:
    - echo "Tagging and pushing container image as stable"
    - skopeo copy docker://${CI_REGISTRY_IMAGE}/ie-model-runner:${CURRENT_TAG} docker://${CI_REGISTRY_IMAGE}/ie-model-runner:stable --dest-creds gitlab-ci-token:${CI_JOB_TOKEN} --src-creds gitlab-ci-token:${CI_JOB_TOKEN}
  needs:
    - job: identify_tag_version
      artifacts: true
    - job: build