---
# Branch (main)
#

stages:
  - build

include:
  # hidden
  - local: .gitlab/orange/main/.hidden.gitlab-ci.yml

  # build (rebake)
  - local: .gitlab/orange/main/rebake.gitlab-ci.yml

  # push (ecr)
  - local: .gitlab/orange/main/push.gitlab-ci.yml
