name: docker build & publish

on:
  workflow_call:
    inputs:
      push:
        description: 'Whether to push the image to registry'
        required: false
        type: boolean
        default: true
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  contents: read

env:
  REGISTRY: awsosml
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: 'true'
      - name: Set Docker Push Flag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_call" ]]; then
            # When called from another workflow, use the input parameter
            echo "push=${{ inputs.push }}" >> $GITHUB_ENV
          elif [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.event_name }}" == "release" ]] || [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "push=true" >> $GITHUB_ENV
          else
            echo "push=false" >> $GITHUB_ENV
          fi
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ github.event_name == 'release' }}
            type=semver,pattern={{raw}},enable=${{ github.event_name == 'release' }}
            type=raw,value=nightly-dev,enable=${{ github.ref == 'refs/heads/main' && github.event_name == 'push' || github.event_name == 'workflow_dispatch'}}
            type=raw,value={{date 'YYYYMMDD-hhmmss' tz='UTC'}},enable=${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.model-runner
          push: ${{ env.push }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
